version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:us-east-1:211125332757:task-definition/bluegreen-deployment:1"
       LoadBalancerInfo:
         ContainerName: "bluegreen"
         ContainerPort: 8080
